version: '2.1'
services:
  sql-client:
    image: flink-sql-client
    build: ./sql-client
    command: sleep 5000
    depends_on:
      - kafka
      - jobmanager
    environment:
      FLINK_JOBMANAGER_HOST: jobmanager
      ZOOKEEPER_CONNECT: zookeeper
      KAFKA_BOOTSTRAP: kafka
      MYSQL_HOST: mysql
  jobmanager:
    image: flink-scala
    build: .
    hostname: "jobmanager"
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
    - ./flink-conf-jobmanager.yaml:/opt/flink/conf/flink-conf.yaml
  taskmanager:
    image: flink-scala
    build: .
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - jobmanager:jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
    - ./flink-conf-taskmanager.yaml:/opt/flink/conf/flink-conf.yaml
  data-generator:
    image: apache/data-generator:1
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      LOG4J_LOGGER_KAFKA: "DEBUG"
      #https://github.com/wurstmeister/kafka-docker#automatically-create-topics
      KAFKA_CREATE_TOPICS: "kafka:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mysql:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password --secure_file_priv=/data
    environment:
      MYSQL_USER: "flink"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "flinksql"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
      - ./data:/data
